import assert from 'node:assert/strict';
import { build } from 'esbuild';
const bundle = await build({ entryPoints: ['src/game.ts'], bundle: true, platform: 'node', format: 'esm', write: false });
const { GameEngine } = await import(`data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].text).toString('base64')}`);
const engine = Object.create(GameEngine.prototype);
const artBundle = await build({ entryPoints: ['src/character-art.ts'], bundle: true, platform: 'node', format: 'esm', write: false });
const { faceCharacter, NUWA_FRAMES } = await import(`data:text/javascript;base64,${Buffer.from(artBundle.outputFiles[0].text).toString('base64')}`);
let uv;
const sprite = { material: { map: { offset: { set: (...values) => { uv = values; } } } }, center: { y: 0 } };
for (const direction of ['up','down','left','right']) {
  faceCharacter({ getObjectByName: () => sprite }, direction);
  assert.deepEqual(uv, NUWA_FRAMES[direction]);
  assert.ok(sprite.center.y >= 0.42 && sprite.center.y < 0.45, 'art stays centered within its tile');
  assert.ok(sprite.center.x >= 0.48 && sprite.center.x <= 0.56);
}
assert.doesNotThrow(() => faceCharacter({ getObjectByName: () => undefined }, 'down'));
console.log('PASS: Nuwa four-direction atlas mapping, foot anchors and legacy actor fallback');
const rulesBundle = await build({ entryPoints: ['src/match-rules.ts'], bundle: true, platform: 'node', format: 'esm', write: false });
const { MATCH_RULES } = await import(`data:text/javascript;base64,${Buffer.from(rulesBundle.outputFiles[0].text).toString('base64')}`);
assert.equal(MATCH_RULES.duration, 120, 'all match modes use a two-minute limit');
const restored = Object.create(GameEngine.prototype);
Object.assign(restored, {
  start() {}, clearGroup() {}, createMapMeshes() {}, updateMeshes() {}, pause() {},
  actors: new Map(), tileMeshes: new Map(), bombs: [], items: [], rng: { importState() {} },
});
for (const [remaining, elapsed, expected] of [[180,0,120],[150,30,90],[40,140,0],[90,30,90]]) {
  restored.restore({ actors: [], bombs: [], items: [], tiles: [], remaining, elapsed });
  assert.equal(restored.remaining, expected, 'resume preserves elapsed time under the new limit');
}
console.log('PASS: two-minute match limit and legacy countdown migration');
const practice = Object.create(GameEngine.prototype);
Object.assign(practice,{practice:true,result:null,remaining:119,actors:new Map([['player',{id:'player',alive:true}]]),listeners:new Set(),running:true});
practice.checkRoundEnd();assert.equal(practice.result,null,'solo trial does not immediately win');
practice.remaining=0;practice.checkRoundEnd();assert.equal(practice.result,'win');
practice.result=null;practice.remaining=90;practice.actors.get('player').alive=false;
practice.checkRoundEnd();assert.equal(practice.result,'lose','trial death ends the round');
practice.result=null;practice.practice=false;practice.actors.get('player').alive=true;
practice.checkRoundEnd();assert.equal(practice.result,'win','normal last-survivor win is unchanged');
console.log('PASS: solo trial continues until timeout or death; normal elimination rule preserved');
const frameClock=Object.create(GameEngine.prototype);
Object.assign(frameClock,{running:true,elapsed:0,remaining:120,coinTimer:5,result:null,updateActors(){},updateBombs(){},updateEffects(){},updateMeshes(){}});
frameClock.update(-0.001);assert.equal(frameClock.remaining,120);assert.equal(frameClock.elapsed,0);
const fresh = () => ({ active: null, armed: false, shield: false, life: false, invincible: 0, dash: 0, rapid: 0, bombCooldown: 0, respawning: false });
const actor = { id: 'player', alive: true, skills: fresh(), position: { x: 1, y: 1 }, bombCapacity: 1, range: 2, speed: 1 };
engine.listeners = new Set();
const pickupEvents = [];
engine.listeners.add(event => { if (event.type === 'item-picked') pickupEvents.push(event); });
engine.items = [];
engine.itemGroup = { children: [] };
for (const [skill, timer] of [['invincible', 3], ['dash', 5], ['rapid', 4]]) {
  actor.skills = fresh(); actor.skills.active = skill;
  engine.useSkill(actor);
  assert.equal(actor.skills[skill], timer);
  assert.equal(actor.skills.active, null);
}
actor.skills.active = 'super';
engine.useSkill(actor); assert.equal(actor.skills.armed, true);
engine.useSkill(actor); assert.equal(actor.skills.armed, false);
engine.items = [{ position: { ...actor.position }, kind: 'dash' }];
engine.collectItem(actor); assert.equal(engine.items.length, 1, 'occupied slot must not auto replace');
assert.equal(pickupEvents.length, 0, 'blocked pickup must not trigger success feedback');
engine.collectItem(actor, true); assert.equal(actor.skills.active, 'dash');
assert.equal(pickupEvents.at(-1).replaced, true, 'explicit replacement has its own feedback');
for (const kind of ['bomb', 'flame', 'speed', 'shield', 'life']) {
  for (let i = 0; i < 10; i++) { engine.items = [{ position: { ...actor.position }, kind }]; engine.collectItem(actor); }
}
assert.equal(actor.bombCapacity, 5); assert.equal(actor.range, 5); assert.equal(actor.speed, 1.3);
assert.equal(actor.skills.shield, true); assert.equal(actor.skills.life, true);
assert.equal(pickupEvents.at(-1).capped, true, 'duplicate life must not claim an upgrade');
assert.ok(pickupEvents.some(event => event.item === 'bomb' && !event.capped));
assert.ok(pickupEvents.some(event => event.item === 'bomb' && event.capped));
engine.tiles = Array.from({ length: 11 }, () => Array(13).fill('floor'));
engine.tiles[1][2] = 'crate'; engine.tiles[1][4] = 'crate'; engine.tiles[0][1] = 'wall';
const normal = engine.getBlastCells(actor.position, 5);
const superCells = engine.getBlastCells(actor.position, 5, true);
assert.equal(normal.some(p => p.x === 3 && p.y === 1), false);
assert.equal(superCells.some(p => p.x === 4 && p.y === 1), true);
assert.equal(superCells.some(p => p.x === 5 && p.y === 1), false);
assert.equal(superCells.some(p => p.x === 1 && p.y === 0), false);
engine.running = false; engine.actors = new Map([['player', actor]]);
actor.skills.active = 'invincible'; engine.usePlayerSkill(); assert.equal(actor.skills.active, 'invincible');
console.log('PASS: active durations, arming, replacement, growth caps, passives, piercing and pause guard');
const ai = Object.create(GameEngine.prototype);
const bot = { id:'a', alive:true, position:{x:1,y:1}, personality:'collector', bombCapacity:2, bombsActive:0 };
const rival = { id:'b', alive:true, position:{x:5,y:1} };
ai.actors=new Map([['player',{id:'player',alive:false,position:{x:2,y:1}}],['a',bot],['b',rival]]);
ai.getDangerKeys=()=>new Set(); ai.findNearest=()=>null; ai.canEscapeAfterBomb=()=>false;
let chosenTarget=null; ai.nextStepToward=(_from,target)=>{chosenTarget=target;return null;};
ai.decideBot(bot); assert.equal(chosenTarget,rival.position,'bots must pursue living rivals after player elimination');
console.log('PASS: AI selects living opponents, including other bots');
engine.removeBombVisuals = () => {};
engine.createExplosionEffect = () => {};
engine.checkRoundEnd = () => {};
actor.group = { visible: true }; actor.name = '测试选手'; actor.bombsActive = 1;
const hit = () => {
  const bomb = { id: 1, ownerId: 'player', position: { ...actor.position }, range: 0 };
  engine.bombs = [bomb]; engine.explodeBomb(bomb);
};
actor.skills = fresh(); actor.skills.invincible = 3; actor.skills.shield = true; actor.skills.life = true;
hit(); assert.equal(actor.skills.shield, true); assert.equal(actor.skills.life, true);
actor.skills.invincible = 0; hit(); assert.equal(actor.skills.shield, false); assert.equal(actor.skills.life, true);
hit(); assert.equal(actor.skills.life, true, 'same chain cannot consume extra life after shield');
actor.skills.invincible = 0; hit(); assert.equal(actor.skills.respawning, true); assert.equal(actor.alive, true);
actor.skills.respawning = false; hit(); assert.equal(actor.alive, false); assert.equal(actor.skills.respawning, false);
actor.alive = true; actor.skills = fresh(); actor.skills.active = 'super'; actor.skills.armed = true; actor.bombsActive = actor.bombCapacity;
assert.equal(engine.placeBomb(actor), false); assert.equal(actor.skills.active, 'super'); assert.equal(actor.skills.armed, true);
console.log('PASS: protection and respawn; failed placement retains super skill');
actor.score = 0; actor.hits = 0; actor.crates = 0;
engine.award('player', 'hit'); engine.award('player', 'crate');
assert.equal(actor.score, 110); assert.equal(actor.hits, 1); assert.equal(actor.crates, 1);
delete engine.checkRoundEnd;
engine.result = null; engine.remaining = 1;
engine.actors.set('bot', { id: 'bot', name: 'Bot', alive: true, score: 100, hits: 1, crates: 0 });
engine.checkRoundEnd(); assert.equal(engine.result, null);
engine.remaining = 0; engine.checkRoundEnd(); assert.equal(engine.result, 'win');
engine.actors.set('bot', { id: 'bot', name: 'Bot', alive: true, score: 110, hits: 0, crates: 11 });
engine.result = null; engine.checkRoundEnd(); assert.equal(engine.result, 'draw');
engine.actors.get('bot').score = 120;
engine.result = null; engine.checkRoundEnd(); assert.equal(engine.result, 'lose');
console.log('PASS: scores, time limit, highest-score winner and ties');
engine.result = null; engine.remaining = 100; engine.actors.get('bot').alive = false;
engine.checkRoundEnd(); assert.equal(engine.result, 'win', 'last survivor wins despite lower score');
engine.result = null; actor.alive = false;
engine.checkRoundEnd(); assert.equal(engine.result, 'draw', 'simultaneous elimination is a draw');
engine.result = null; engine.remaining = 0; actor.score = 9999;
engine.actors.get('bot').alive = true;
engine.actors.set('bot2', { id: 'bot2', name: 'Bot2', alive: true, score: 10, hits: 0, crates: 1 });
engine.checkRoundEnd(); assert.equal(engine.result, 'lose', 'eliminated player cannot win on points');
console.log('PASS: elimination, survival victory, mutual elimination and survivor-only points');
actor.alive = true; actor.skills = fresh(); actor.skills.active = 'super'; actor.score = 0;
engine.items = [{ kind: 'coin', position: { ...actor.position } }];
engine.collectItem(actor); engine.collectItem(actor);
assert.equal(actor.score, 5, 'one coin awards exactly five points once');
assert.equal(actor.skills.active, 'super', 'coin does not replace skill');
engine.actors = new Map([['player', actor]]); engine.items = []; engine.bombs = [];
engine.rng = { next: () => 0.5 }; engine.createItemMesh = () => {};
for (let i = 0; i < 10; i++) engine.spawnCoin();
assert.equal(engine.items.length, 6);
assert.equal(new Set(engine.items.map(i => `${i.position.x},${i.position.y}`)).size, 6);
assert.ok(engine.items.every(i => engine.tiles[i.position.y][i.position.x] === 'floor'));
assert.ok(engine.items.every(i => i.position.x !== actor.position.x || i.position.y !== actor.position.y));
console.log('PASS: coin score, single collection, skill preservation, spawn cap and safe placement');
