import assert from 'node:assert/strict';
import { build } from 'esbuild';
async function load(path){const b=await build({entryPoints:[path],bundle:true,platform:'node',format:'esm',write:false});return import(`data:text/javascript;base64,${Buffer.from(b.outputFiles[0].text).toString('base64')}`);}
const {createSaveStore}=await load('src/shared/save-store.ts');
const {initialSave,validateSave,savedMatchSlots}=await load('src/save.ts');
const {createTournament,submitMatch,advance}=await load('src/tournament.ts');
const {settleQuick,settleTournament}=await load('src/career.ts');
const memory=new Map(); const storage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)};
const store=createSaveStore('test',validateSave,storage);
const save=initialSave(); assert.ok(validateSave(save));
await store.write(save,0); assert.equal(store.load().revision,1);
await assert.rejects(()=>store.write(save,0),/标签页/);
await store.write(save,1); assert.equal(store.backup().revision,1);
assert.throws(()=>store.parse('{"version":3}'));
assert.equal(validateSave({...save,active:{}}),false);
const rows=[{id:'player',score:10,hits:1,crates:1,alive:true},{id:'0',score:0,hits:0,crates:0,alive:false}];
settleQuick(save.career,'quick-1','hard',rows); const points=save.career.points.player;
assert.equal(points,192);settleQuick(save.career,'quick-1','hard',rows);assert.equal(save.career.points.player,points);
save.tournament=createTournament('normal');
while(save.tournament.round!=='complete'){
  for(const m of save.tournament.matches)submitMatch(save.tournament,m,m.members.map((id,i)=>({id,score:100-i,hits:1,crates:0,alive:true})));
  advance(save.tournament);settleTournament(save.career,save.tournament);
  assert.ok(validateSave(save),`valid ${save.tournament.round} save`);
}
const before=JSON.stringify(save.career);settleTournament(save.career,save.tournament);assert.equal(JSON.stringify(save.career),before);
assert.equal(save.career.history.length,2);
await store.write(save,2);assert.ok(validateSave(store.load().data));
console.log('PASS: version/checksum validation, backup, conflict, difficulty score, idempotent awards and all tournament save stages');
await assert.rejects(()=>store.recover(save),/当前存档有效/);
storage.setItem('test','broken');await store.recover(save);
assert.equal(storage.getItem('test:damaged'),'broken');assert.ok(validateSave(store.load().data));
const {equipCosmetic}=await load('src/cosmetics.ts');
const wardrobe=initialSave();assert.equal(equipCosmetic(wardrobe.career,wardrobe.settings,'mint'),false);
wardrobe.career.coins=120;assert.equal(equipCosmetic(wardrobe.career,wardrobe.settings,'mint'),true);
assert.equal(wardrobe.career.coins,0);assert.equal(equipCosmetic(wardrobe.career,wardrobe.settings,'mint'),true);
assert.ok(validateSave(wardrobe));assert.equal(equipCosmetic(wardrobe.career,wardrobe.settings,'invalid'),false);
console.log('PASS: damaged-save recovery preserves original; cosmetic purchases charge once');
const legacy=initialSave();
assert.deepEqual(savedMatchSlots(legacy),{quick:null,championship:null});
const quick={id:'quick-snapshot',mode:'quick',snapshot:{}};
const championship={id:'championship-snapshot',mode:'championship',snapshot:{}};
legacy.active=quick;
assert.deepEqual(savedMatchSlots(legacy),{quick,championship:null});
legacy.active=championship;
assert.deepEqual(savedMatchSlots(legacy),{quick:null,championship});
legacy.matches={quick,championship};
assert.deepEqual(savedMatchSlots(legacy),{quick,championship});
assert.equal(validateSave({...initialSave(),matches:{quick:null,championship:null}}),true);
assert.equal(validateSave({...initialSave(),matches:{quick:championship,championship:null}}),false);
assert.equal(validateSave({...initialSave(),matches:{}}),false);
console.log('PASS: legacy save migration, separate match slots and invalid-slot rejection');
